[build]
  # Change this to match your actual folder path in GitHub
  base = "bose/public-verify-app"
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200